version: '3.1'

volumes:
  postgres-data: ~

services:
  app:
    build:
      context: ./docker/app
      args:
        UID: ${DEV_UID}
    depends_on:
      - db
    environment:
      - APP_HOSTNAME
      - APP_HOST_PORT
      - DATABASE_HOST=db
      - DATABASE_NAME
      - DATABASE_PASSWORD_FILE=/var/run/secrets/DATABASE_PASSWORD
      - DATABASE_USERNAME_FILE=/var/run/secrets/DATABASE_USERNAME
      - LIVE_VIEW_SIGNING_SALT
      - SECRET_KEY_BASE_FILE=/var/run/secrets/SECRET_KEY_BASE
      - MIX_ENV=dev
    volumes:
      - .:/opt/app
      - ./docker/secrets:/var/run/secrets

  nginx:
    image: nginx:1.19-alpine
    ports:
      - ${APP_HOST_PORT}:80
    links:
      - app
    volumes:
      - ./priv/static:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf

  db:
    image: 'postgres:12-alpine'
    volumes:
      - ./docker/secrets:/var/run/secrets
      - postgres-data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD_FILE=/var/run/secrets/DATABASE_PASSWORD
      - POSTGRES_USER_FILE=/var/run/secrets/DATABASE_USERNAME
      - POSTGRES_HOST_AUTH_METHOD=trust
